# Generated by Django 3.1.7 on 2021-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='alias',
        ),
        migrations.AddField(
            model_name='hero',
            name='ingredients',
            field=models.CharField(default=None, max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=600),
        ),
    ]
